# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'VtnaBuscar.ui'
##
## Created by: Qt User Interface Compiler version 5.15.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_BuscarProducto(object):
    def setupUi(self, BuscarProducto):
        if not BuscarProducto.objectName():
            BuscarProducto.setObjectName(u"BuscarProducto")
        BuscarProducto.resize(1381, 720)
        font = QFont()
        font.setPointSize(12)
        BuscarProducto.setFont(font)
        icon = QIcon()
        icon.addFile(u"../../Logo.ico", QSize(), QIcon.Normal, QIcon.On)
        BuscarProducto.setWindowIcon(icon)
        self.centralwidget = QWidget(BuscarProducto)
        self.centralwidget.setObjectName(u"centralwidget")
        self.push_op1 = QPushButton(self.centralwidget)
        self.push_op1.setObjectName(u"push_op1")
        self.push_op1.setGeometry(QRect(150, 10, 131, 101))
        self.push_op1.setFont(font)
        self.push_op2 = QPushButton(self.centralwidget)
        self.push_op2.setObjectName(u"push_op2")
        self.push_op2.setGeometry(QRect(150, 110, 131, 101))
        self.push_op2.setFont(font)
        self.push_Repuesto = QPushButton(self.centralwidget)
        self.push_Repuesto.setObjectName(u"push_Repuesto")
        self.push_Repuesto.setGeometry(QRect(10, 10, 131, 101))
        font1 = QFont()
        font1.setFamily(u"Arial Black")
        font1.setPointSize(12)
        font1.setBold(True)
        font1.setWeight(75)
        self.push_Repuesto.setFont(font1)
        self.push_Bazar = QPushButton(self.centralwidget)
        self.push_Bazar.setObjectName(u"push_Bazar")
        self.push_Bazar.setGeometry(QRect(10, 110, 131, 101))
        font2 = QFont()
        font2.setFamily(u"Arial Black")
        font2.setPointSize(10)
        font2.setBold(True)
        font2.setWeight(75)
        self.push_Bazar.setFont(font2)
        self.push_op3 = QPushButton(self.centralwidget)
        self.push_op3.setObjectName(u"push_op3")
        self.push_op3.setGeometry(QRect(150, 210, 131, 101))
        self.push_op3.setFont(font)
        self.push_PedidosEsp = QPushButton(self.centralwidget)
        self.push_PedidosEsp.setObjectName(u"push_PedidosEsp")
        self.push_PedidosEsp.setGeometry(QRect(10, 310, 131, 101))
        self.push_PedidosEsp.setFont(font2)
        self.push_Otros = QPushButton(self.centralwidget)
        self.push_Otros.setObjectName(u"push_Otros")
        self.push_Otros.setGeometry(QRect(10, 410, 131, 101))
        self.push_Otros.setFont(font1)
        self.push_Aventas = QPushButton(self.centralwidget)
        self.push_Aventas.setObjectName(u"push_Aventas")
        self.push_Aventas.setGeometry(QRect(10, 210, 131, 101))
        self.push_Aventas.setFont(font2)
        self.push_op6 = QPushButton(self.centralwidget)
        self.push_op6.setObjectName(u"push_op6")
        self.push_op6.setGeometry(QRect(150, 510, 131, 101))
        self.push_op6.setFont(font)
        self.push_op5 = QPushButton(self.centralwidget)
        self.push_op5.setObjectName(u"push_op5")
        self.push_op5.setGeometry(QRect(150, 410, 131, 101))
        self.push_op5.setFont(font)
        self.push_op5.setStyleSheet(u"")
        self.push_op4 = QPushButton(self.centralwidget)
        self.push_op4.setObjectName(u"push_op4")
        self.push_op4.setGeometry(QRect(150, 310, 131, 101))
        self.push_op4.setFont(font)
        self.push_Cargar = QPushButton(self.centralwidget)
        self.push_Cargar.setObjectName(u"push_Cargar")
        self.push_Cargar.setGeometry(QRect(10, 610, 131, 101))
        icon1 = QIcon()
        icon1.addFile(u"icon/cargar.png", QSize(), QIcon.Disabled, QIcon.On)
        self.push_Cargar.setIcon(icon1)
        self.push_Cargar.setIconSize(QSize(70, 70))
        self.push_Cancelar = QPushButton(self.centralwidget)
        self.push_Cancelar.setObjectName(u"push_Cancelar")
        self.push_Cancelar.setGeometry(QRect(10, 510, 131, 101))
        icon2 = QIcon()
        icon2.addFile(u"icon/cancelar2.png", QSize(), QIcon.Disabled, QIcon.On)
        self.push_Cancelar.setIcon(icon2)
        self.push_Cancelar.setIconSize(QSize(70, 70))
        self.push_1 = QPushButton(self.centralwidget)
        self.push_1.setObjectName(u"push_1")
        self.push_1.setGeometry(QRect(290, 10, 191, 131))
        self.push_1.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);\n"
"\n"
"\n"
"")
        self.push_4 = QPushButton(self.centralwidget)
        self.push_4.setObjectName(u"push_4")
        self.push_4.setGeometry(QRect(860, 10, 191, 131))
        self.push_4.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_Adelante = QPushButton(self.centralwidget)
        self.push_Adelante.setObjectName(u"push_Adelante")
        self.push_Adelante.setGeometry(QRect(1250, 350, 111, 311))
        icon3 = QIcon()
        icon3.addFile(u"icon/siguiente.png", QSize(), QIcon.Normal, QIcon.On)
        self.push_Adelante.setIcon(icon3)
        self.push_Adelante.setIconSize(QSize(60, 60))
        self.push_9 = QPushButton(self.centralwidget)
        self.push_9.setObjectName(u"push_9")
        self.push_9.setGeometry(QRect(860, 180, 191, 131))
        self.push_9.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_3 = QPushButton(self.centralwidget)
        self.push_3.setObjectName(u"push_3")
        self.push_3.setGeometry(QRect(670, 10, 191, 131))
        self.push_3.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_Atras = QPushButton(self.centralwidget)
        self.push_Atras.setObjectName(u"push_Atras")
        self.push_Atras.setGeometry(QRect(1250, 50, 111, 311))
        icon4 = QIcon()
        icon4.addFile(u"icon/anterior.png", QSize(), QIcon.Normal, QIcon.On)
        self.push_Atras.setIcon(icon4)
        self.push_Atras.setIconSize(QSize(60, 60))
        self.push_8 = QPushButton(self.centralwidget)
        self.push_8.setObjectName(u"push_8")
        self.push_8.setGeometry(QRect(670, 180, 191, 131))
        self.push_8.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_6 = QPushButton(self.centralwidget)
        self.push_6.setObjectName(u"push_6")
        self.push_6.setGeometry(QRect(290, 180, 191, 131))
        self.push_6.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_5 = QPushButton(self.centralwidget)
        self.push_5.setObjectName(u"push_5")
        self.push_5.setGeometry(QRect(1050, 10, 191, 131))
        self.push_5.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_10 = QPushButton(self.centralwidget)
        self.push_10.setObjectName(u"push_10")
        self.push_10.setGeometry(QRect(1050, 180, 191, 131))
        self.push_10.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_7 = QPushButton(self.centralwidget)
        self.push_7.setObjectName(u"push_7")
        self.push_7.setGeometry(QRect(480, 180, 191, 131))
        self.push_7.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_2 = QPushButton(self.centralwidget)
        self.push_2.setObjectName(u"push_2")
        self.push_2.setGeometry(QRect(480, 10, 191, 131))
        self.push_2.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_11 = QPushButton(self.centralwidget)
        self.push_11.setObjectName(u"push_11")
        self.push_11.setGeometry(QRect(290, 350, 191, 131))
        self.push_11.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_12 = QPushButton(self.centralwidget)
        self.push_12.setObjectName(u"push_12")
        self.push_12.setGeometry(QRect(480, 350, 191, 131))
        self.push_12.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_13 = QPushButton(self.centralwidget)
        self.push_13.setObjectName(u"push_13")
        self.push_13.setGeometry(QRect(670, 350, 191, 131))
        self.push_13.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_14 = QPushButton(self.centralwidget)
        self.push_14.setObjectName(u"push_14")
        self.push_14.setGeometry(QRect(860, 350, 191, 131))
        self.push_14.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_15 = QPushButton(self.centralwidget)
        self.push_15.setObjectName(u"push_15")
        self.push_15.setGeometry(QRect(1050, 350, 191, 131))
        self.push_15.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_16 = QPushButton(self.centralwidget)
        self.push_16.setObjectName(u"push_16")
        self.push_16.setGeometry(QRect(290, 520, 191, 131))
        self.push_16.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_17 = QPushButton(self.centralwidget)
        self.push_17.setObjectName(u"push_17")
        self.push_17.setGeometry(QRect(480, 520, 191, 131))
        self.push_17.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_18 = QPushButton(self.centralwidget)
        self.push_18.setObjectName(u"push_18")
        self.push_18.setGeometry(QRect(670, 520, 191, 131))
        self.push_18.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_19 = QPushButton(self.centralwidget)
        self.push_19.setObjectName(u"push_19")
        self.push_19.setGeometry(QRect(860, 520, 191, 131))
        self.push_19.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_20 = QPushButton(self.centralwidget)
        self.push_20.setObjectName(u"push_20")
        self.push_20.setGeometry(QRect(1050, 520, 191, 131))
        self.push_20.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.label_1 = QLabel(self.centralwidget)
        self.label_1.setObjectName(u"label_1")
        self.label_1.setGeometry(QRect(290, 140, 191, 20))
        font3 = QFont()
        font3.setFamily(u"Calibri")
        font3.setPointSize(11)
        font3.setBold(True)
        font3.setItalic(True)
        font3.setWeight(75)
        self.label_1.setFont(font3)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(480, 140, 191, 20))
        self.label_2.setFont(font3)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(670, 140, 191, 20))
        self.label_3.setFont(font3)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(860, 140, 191, 20))
        self.label_4.setFont(font3)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(1050, 140, 191, 20))
        self.label_5.setFont(font3)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(290, 310, 191, 20))
        self.label_6.setFont(font3)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(480, 310, 191, 20))
        self.label_7.setFont(font3)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(670, 310, 191, 20))
        self.label_8.setFont(font3)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(860, 310, 191, 20))
        self.label_9.setFont(font3)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(1050, 310, 191, 20))
        self.label_10.setFont(font3)
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(480, 480, 191, 20))
        self.label_12.setFont(font3)
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(670, 480, 191, 20))
        self.label_13.setFont(font3)
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(860, 480, 191, 20))
        self.label_14.setFont(font3)
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(1050, 480, 191, 20))
        self.label_15.setFont(font3)
        self.label_16 = QLabel(self.centralwidget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(290, 650, 191, 20))
        self.label_16.setFont(font3)
        self.label_17 = QLabel(self.centralwidget)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(480, 650, 191, 20))
        self.label_17.setFont(font3)
        self.label_18 = QLabel(self.centralwidget)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(670, 650, 191, 20))
        self.label_18.setFont(font3)
        self.label_19 = QLabel(self.centralwidget)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(860, 650, 191, 20))
        self.label_19.setFont(font3)
        self.label_20 = QLabel(self.centralwidget)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(1050, 650, 191, 20))
        self.label_20.setFont(font3)
        self.push_op7 = QPushButton(self.centralwidget)
        self.push_op7.setObjectName(u"push_op7")
        self.push_op7.setGeometry(QRect(150, 610, 131, 101))
        self.push_op7.setFont(font)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(290, 480, 191, 20))
        self.label_11.setFont(font3)
        BuscarProducto.setCentralWidget(self.centralwidget)
        QWidget.setTabOrder(self.push_Repuesto, self.push_Bazar)
        QWidget.setTabOrder(self.push_Bazar, self.push_Aventas)
        QWidget.setTabOrder(self.push_Aventas, self.push_PedidosEsp)
        QWidget.setTabOrder(self.push_PedidosEsp, self.push_Otros)
        QWidget.setTabOrder(self.push_Otros, self.push_op1)
        QWidget.setTabOrder(self.push_op1, self.push_op2)
        QWidget.setTabOrder(self.push_op2, self.push_op3)
        QWidget.setTabOrder(self.push_op3, self.push_op4)
        QWidget.setTabOrder(self.push_op4, self.push_op5)
        QWidget.setTabOrder(self.push_op5, self.push_op6)
        QWidget.setTabOrder(self.push_op6, self.push_Atras)
        QWidget.setTabOrder(self.push_Atras, self.push_Adelante)
        QWidget.setTabOrder(self.push_Adelante, self.push_Cargar)
        QWidget.setTabOrder(self.push_Cargar, self.push_Cancelar)

        self.retranslateUi(BuscarProducto)

        QMetaObject.connectSlotsByName(BuscarProducto)
    # setupUi

    def retranslateUi(self, BuscarProducto):
        BuscarProducto.setWindowTitle(QCoreApplication.translate("BuscarProducto", u"Buscar Producto", None))
        self.push_op1.setText(QCoreApplication.translate("BuscarProducto", u"-", None))
        self.push_op2.setText(QCoreApplication.translate("BuscarProducto", u"-", None))
        self.push_Repuesto.setText(QCoreApplication.translate("BuscarProducto", u"REPUESTO", None))
        self.push_Bazar.setText(QCoreApplication.translate("BuscarProducto", u"BAZAR PREMIUM", None))
        self.push_op3.setText(QCoreApplication.translate("BuscarProducto", u"-", None))
        self.push_PedidosEsp.setText(QCoreApplication.translate("BuscarProducto", u"PEDIDOS ESPEC.", None))
        self.push_Otros.setText(QCoreApplication.translate("BuscarProducto", u"OTROS", None))
        self.push_Aventas.setText(QCoreApplication.translate("BuscarProducto", u"AYUDA VNTS", None))
        self.push_op6.setText(QCoreApplication.translate("BuscarProducto", u"-", None))
        self.push_op5.setText(QCoreApplication.translate("BuscarProducto", u"-", None))
        self.push_op4.setText(QCoreApplication.translate("BuscarProducto", u"-", None))
        self.push_Cargar.setText("")
        self.push_Cancelar.setText("")
        self.push_1.setText("")
        self.push_4.setText("")
        self.push_Adelante.setText("")
        self.push_9.setText("")
        self.push_3.setText("")
        self.push_Atras.setText("")
        self.push_8.setText("")
        self.push_6.setText("")
        self.push_5.setText("")
        self.push_10.setText("")
        self.push_7.setText("")
        self.push_2.setText("")
        self.push_11.setText("")
        self.push_12.setText("")
        self.push_13.setText("")
        self.push_14.setText("")
        self.push_15.setText("")
        self.push_16.setText("")
        self.push_17.setText("")
        self.push_18.setText("")
        self.push_19.setText("")
        self.push_20.setText("")
        self.label_1.setText("")
        self.label_2.setText("")
        self.label_3.setText("")
        self.label_4.setText("")
        self.label_5.setText("")
        self.label_6.setText("")
        self.label_7.setText("")
        self.label_8.setText("")
        self.label_9.setText("")
        self.label_10.setText("")
        self.label_12.setText("")
        self.label_13.setText("")
        self.label_14.setText("")
        self.label_15.setText("")
        self.label_16.setText("")
        self.label_17.setText("")
        self.label_18.setText("")
        self.label_19.setText("")
        self.label_20.setText("")
        self.push_op7.setText(QCoreApplication.translate("BuscarProducto", u"-", None))
        self.label_11.setText("")
    # retranslateUi

