# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'VtnaVentas.ui'
##
## Created by: Qt User Interface Compiler version 5.15.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_VentasBD(object):
    def setupUi(self, VentasBD):
        if not VentasBD.objectName():
            VentasBD.setObjectName(u"VentasBD")
        VentasBD.resize(1366, 700)
        self.label_17 = QLabel(VentasBD)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(980, 370, 141, 31))
        font = QFont()
        font.setFamily(u"Calibri")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label = QLabel(VentasBD)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(270, 70, 371, 41))
        font1 = QFont()
        font1.setFamily(u"Courier")
        font1.setPointSize(16)
        font1.setBold(True)
        font1.setItalic(True)
        font1.setWeight(75)
        self.label.setFont(font1)
        self.label.setStyleSheet(u"background-color: rgb(255, 220, 92);")
        self.push_Bproduc = QPushButton(VentasBD)
        self.push_Bproduc.setObjectName(u"push_Bproduc")
        self.push_Bproduc.setGeometry(QRect(50, 170, 131, 71))
        font2 = QFont()
        font2.setFamily(u"Arial Black")
        font2.setPointSize(10)
        font2.setBold(True)
        font2.setWeight(75)
        self.push_Bproduc.setFont(font2)
        self.push_Bproduc.setAutoDefault(False)
        self.label_15 = QLabel(VentasBD)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(320, 600, 47, 20))
        font3 = QFont()
        font3.setFamily(u"Candara")
        font3.setPointSize(11)
        font3.setBold(True)
        font3.setItalic(True)
        font3.setWeight(75)
        self.label_15.setFont(font3)
        self.listView_2 = QListView(VentasBD)
        self.listView_2.setObjectName(u"listView_2")
        self.listView_2.setGeometry(QRect(440, 320, 71, 281))
        font4 = QFont()
        font4.setFamily(u"Calibri")
        font4.setPointSize(10)
        self.listView_2.setFont(font4)
        self.lineEdit_6 = QLineEdit(VentasBD)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(370, 600, 71, 20))
        font5 = QFont()
        font5.setFamily(u"Calibri")
        font5.setPointSize(10)
        font5.setBold(True)
        font5.setWeight(75)
        self.lineEdit_6.setFont(font5)
        self.lineEdit_6.setAlignment(Qt.AlignCenter)
        self.push_Menu = QPushButton(VentasBD)
        self.push_Menu.setObjectName(u"push_Menu")
        self.push_Menu.setGeometry(QRect(1170, 600, 160, 80))
        font6 = QFont()
        font6.setFamily(u"Arial Black")
        font6.setPointSize(16)
        font6.setBold(True)
        font6.setItalic(True)
        font6.setWeight(75)
        self.push_Menu.setFont(font6)
        icon = QIcon()
        icon.addFile(u"MainW/icon/home.png", QSize(), QIcon.Normal, QIcon.On)
        self.push_Menu.setIcon(icon)
        self.push_Menu.setIconSize(QSize(60, 60))
        self.push_Menu.setAutoDefault(False)
        self.lineEdit_12 = QLineEdit(VentasBD)
        self.lineEdit_12.setObjectName(u"lineEdit_12")
        self.lineEdit_12.setGeometry(QRect(1050, 620, 61, 31))
        font7 = QFont()
        font7.setFamily(u"Calibri")
        font7.setPointSize(14)
        font7.setBold(True)
        font7.setWeight(75)
        self.lineEdit_12.setFont(font7)
        self.lineEdit_12.setStyleSheet(u"")
        self.lineEdit_12.setAlignment(Qt.AlignCenter)
        self.label_2 = QLabel(VentasBD)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(910, 40, 121, 31))
        font8 = QFont()
        font8.setFamily(u"Javanese Text")
        font8.setPointSize(14)
        font8.setBold(True)
        font8.setItalic(True)
        font8.setWeight(75)
        self.label_2.setFont(font8)
        self.label_12 = QLabel(VentasBD)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(450, 300, 61, 16))
        font9 = QFont()
        font9.setFamily(u"Candara")
        font9.setPointSize(12)
        font9.setBold(True)
        font9.setItalic(True)
        font9.setWeight(75)
        self.label_12.setFont(font9)
        self.label_11 = QLabel(VentasBD)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(370, 300, 61, 16))
        self.label_11.setFont(font9)
        self.label_25 = QLabel(VentasBD)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(980, 410, 141, 31))
        self.label_25.setFont(font)
        self.comboBox = QComboBox(VentasBD)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(1050, 40, 201, 31))
        self.comboBox.setFont(font)
        self.lineEdit_9 = QLineEdit(VentasBD)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setGeometry(QRect(580, 600, 71, 20))
        self.lineEdit_9.setFont(font5)
        self.lineEdit_9.setAlignment(Qt.AlignCenter)
        self.push_Limpiar = QPushButton(VentasBD)
        self.push_Limpiar.setObjectName(u"push_Limpiar")
        self.push_Limpiar.setGeometry(QRect(1170, 390, 160, 80))
        self.push_Limpiar.setFont(font6)
        icon1 = QIcon()
        icon1.addFile(u"MainW/icon/limpiararchivo2.png", QSize(), QIcon.Normal, QIcon.On)
        self.push_Limpiar.setIcon(icon1)
        self.push_Limpiar.setIconSize(QSize(60, 60))
        self.push_Limpiar.setAutoDefault(False)
        self.push_Descuento = QPushButton(VentasBD)
        self.push_Descuento.setObjectName(u"push_Descuento")
        self.push_Descuento.setGeometry(QRect(510, 170, 131, 71))
        self.push_Descuento.setFont(font2)
        self.push_Descuento.setAutoDefault(False)
        self.label_27 = QLabel(VentasBD)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(690, 620, 251, 31))
        self.label_27.setFont(font8)
        self.label_20 = QLabel(VentasBD)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(980, 580, 141, 31))
        self.label_20.setFont(font)
        self.label_28 = QLabel(VentasBD)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(980, 460, 141, 31))
        self.label_28.setFont(font)
        self.label_14 = QLabel(VentasBD)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(590, 300, 61, 16))
        self.label_14.setFont(font9)
        self.push_Bproduc_2 = QPushButton(VentasBD)
        self.push_Bproduc_2.setObjectName(u"push_Bproduc_2")
        self.push_Bproduc_2.setGeometry(QRect(110, 610, 51, 41))
        self.push_Bproduc_2.setFont(font2)
        icon2 = QIcon()
        icon2.addFile(u"MainW/icon/goma.png", QSize(), QIcon.Normal, QIcon.Off)
        self.push_Bproduc_2.setIcon(icon2)
        self.push_Bproduc_2.setIconSize(QSize(40, 40))
        self.push_Bproduc_2.setAutoDefault(False)
        self.push_Cprecio = QPushButton(VentasBD)
        self.push_Cprecio.setObjectName(u"push_Cprecio")
        self.push_Cprecio.setGeometry(QRect(360, 170, 131, 71))
        self.push_Cprecio.setFont(font2)
        self.push_Cprecio.setAutoDefault(False)
        self.label_19 = QLabel(VentasBD)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(690, 540, 251, 31))
        self.label_19.setFont(font8)
        self.label_18 = QLabel(VentasBD)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(980, 540, 141, 31))
        self.label_18.setFont(font)
        self.push_Buscar = QPushButton(VentasBD)
        self.push_Buscar.setObjectName(u"push_Buscar")
        self.push_Buscar.setGeometry(QRect(50, 50, 160, 80))
        self.push_Buscar.setFont(font6)
        icon3 = QIcon()
        icon3.addFile(u"MainW/icon/buscar persona.png", QSize(), QIcon.Normal, QIcon.On)
        self.push_Buscar.setIcon(icon3)
        self.push_Buscar.setIconSize(QSize(60, 60))
        self.push_Buscar.setAutoDefault(False)
        self.label_22 = QLabel(VentasBD)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(690, 580, 251, 31))
        self.label_22.setFont(font8)
        self.push_Registro = QPushButton(VentasBD)
        self.push_Registro.setObjectName(u"push_Registro")
        self.push_Registro.setGeometry(QRect(1170, 510, 160, 80))
        self.push_Registro.setFont(font6)
        icon4 = QIcon()
        icon4.addFile(u"MainW/icon/registros5.png", QSize(), QIcon.Normal, QIcon.On)
        self.push_Registro.setIcon(icon4)
        self.push_Registro.setIconSize(QSize(60, 60))
        self.push_Registro.setAutoDefault(False)
        self.listView_5 = QListView(VentasBD)
        self.listView_5.setObjectName(u"listView_5")
        self.listView_5.setGeometry(QRect(580, 320, 71, 281))
        self.listView_5.setFont(font4)
        self.groupBox = QGroupBox(VentasBD)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(680, 120, 451, 231))
        self.checkBox = QCheckBox(self.groupBox)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(30, 20, 91, 31))
        self.checkBox.setFont(font8)
        self.checkBox_2 = QCheckBox(self.groupBox)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(30, 106, 181, 21))
        self.checkBox_2.setFont(font8)
        self.checkBox_3 = QCheckBox(self.groupBox)
        self.checkBox_3.setObjectName(u"checkBox_3")
        self.checkBox_3.setGeometry(QRect(30, 140, 201, 31))
        self.checkBox_3.setFont(font8)
        self.checkBox_4 = QCheckBox(self.groupBox)
        self.checkBox_4.setObjectName(u"checkBox_4")
        self.checkBox_4.setGeometry(QRect(30, 180, 191, 31))
        self.checkBox_4.setFont(font8)
        self.lineEdit = QLineEdit(self.groupBox)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(320, 20, 101, 20))
        self.lineEdit.setFont(font)
        self.lineEdit.setAlignment(Qt.AlignCenter)
        self.lineEdit_2 = QLineEdit(self.groupBox)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(320, 100, 101, 20))
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setAlignment(Qt.AlignCenter)
        self.lineEdit_3 = QLineEdit(self.groupBox)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(320, 140, 101, 20))
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setAlignment(Qt.AlignCenter)
        self.lineEdit_4 = QLineEdit(self.groupBox)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(320, 180, 101, 20))
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setAlignment(Qt.AlignCenter)
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(300, 20, 21, 21))
        self.label_4.setFont(font8)
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(300, 60, 21, 21))
        self.label_5.setFont(font8)
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(300, 100, 21, 21))
        self.label_6.setFont(font8)
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(300, 140, 21, 21))
        self.label_7.setFont(font8)
        self.label_16 = QLabel(self.groupBox)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(300, 180, 21, 21))
        self.label_16.setFont(font8)
        self.lineEdit_15 = QLineEdit(self.groupBox)
        self.lineEdit_15.setObjectName(u"lineEdit_15")
        self.lineEdit_15.setGeometry(QRect(320, 60, 101, 20))
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setAlignment(Qt.AlignCenter)
        self.label_3 = QLabel(VentasBD)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(720, 100, 231, 31))
        font10 = QFont()
        font10.setFamily(u"DejaVu Sans")
        font10.setPointSize(18)
        font10.setBold(True)
        font10.setItalic(True)
        font10.setWeight(75)
        self.label_3.setFont(font10)
        self.label_3.setStyleSheet(u"color: rgb(0, 0, 255);")
        self.listView = QListView(VentasBD)
        self.listView.setObjectName(u"listView")
        self.listView.setGeometry(QRect(50, 320, 321, 281))
        self.listView.setFont(font4)
        self.push_Guardar = QPushButton(VentasBD)
        self.push_Guardar.setObjectName(u"push_Guardar")
        self.push_Guardar.setGeometry(QRect(1170, 300, 160, 80))
        self.push_Guardar.setFont(font6)
        icon5 = QIcon()
        icon5.addFile(u"MainW/icon/guardararchivo.png", QSize(), QIcon.Normal, QIcon.On)
        self.push_Guardar.setIcon(icon5)
        self.push_Guardar.setIconSize(QSize(60, 60))
        self.push_Guardar.setAutoDefault(False)
        self.label_29 = QLabel(VentasBD)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(690, 460, 251, 31))
        self.label_29.setFont(font8)
        self.push_Bcombo = QPushButton(VentasBD)
        self.push_Bcombo.setObjectName(u"push_Bcombo")
        self.push_Bcombo.setGeometry(QRect(210, 170, 131, 71))
        self.push_Bcombo.setFont(font2)
        self.push_Bcombo.setAutoDefault(False)
        self.label_10 = QLabel(VentasBD)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(180, 299, 91, 21))
        self.label_10.setFont(font9)
        self.lineEdit_7 = QLineEdit(VentasBD)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(440, 600, 71, 20))
        self.lineEdit_7.setFont(font5)
        self.lineEdit_7.setAlignment(Qt.AlignCenter)
        self.label_26 = QLabel(VentasBD)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(690, 420, 251, 31))
        self.label_26.setFont(font8)
        self.label_8 = QLabel(VentasBD)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(690, 380, 251, 31))
        self.label_8.setFont(font8)
        self.lineEdit_8 = QLineEdit(VentasBD)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setGeometry(QRect(510, 600, 71, 20))
        self.lineEdit_8.setFont(font5)
        self.lineEdit_8.setAlignment(Qt.AlignCenter)
        self.label_13 = QLabel(VentasBD)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(530, 300, 47, 13))
        self.label_13.setFont(font9)
        self.listView_3 = QListView(VentasBD)
        self.listView_3.setObjectName(u"listView_3")
        self.listView_3.setGeometry(QRect(370, 320, 71, 281))
        self.listView_3.setFont(font4)
        self.listView_4 = QListView(VentasBD)
        self.listView_4.setObjectName(u"listView_4")
        self.listView_4.setGeometry(QRect(510, 320, 71, 281))
        self.listView_4.setFont(font4)

        self.retranslateUi(VentasBD)

        QMetaObject.connectSlotsByName(VentasBD)
    # setupUi

    def retranslateUi(self, VentasBD):
        VentasBD.setWindowTitle(QCoreApplication.translate("VentasBD", u"Dialog", None))
        self.label_17.setText("")
        self.label.setText("")
        self.push_Bproduc.setText(QCoreApplication.translate("VentasBD", u"Buscar Producto", None))
        self.label_15.setText(QCoreApplication.translate("VentasBD", u"TOTAL", None))
        self.lineEdit_6.setText("")
        self.push_Menu.setText("")
        self.lineEdit_12.setText("")
        self.label_2.setText(QCoreApplication.translate("VentasBD", u"VENDEDOR", None))
        self.label_12.setText(QCoreApplication.translate("VentasBD", u"PC + 10%", None))
        self.label_11.setText(QCoreApplication.translate("VentasBD", u"P. COSTO", None))
        self.label_25.setText("")
        self.lineEdit_9.setText("")
        self.push_Limpiar.setText("")
        self.push_Descuento.setText(QCoreApplication.translate("VentasBD", u"Aplicar Desc.", None))
        self.label_27.setText(QCoreApplication.translate("VentasBD", u"PUNTOS", None))
        self.label_20.setText("")
        self.label_28.setText("")
        self.label_14.setText(QCoreApplication.translate("VentasBD", u"P. LISTA", None))
        self.push_Bproduc_2.setText("")
        self.push_Cprecio.setText(QCoreApplication.translate("VentasBD", u"Cambiar Precio", None))
        self.label_19.setText(QCoreApplication.translate("VentasBD", u"Ganancia Total de la venta", None))
        self.label_18.setText("")
        self.push_Buscar.setText("")
        self.label_22.setText(QCoreApplication.translate("VentasBD", u"Porcentaje de Ganancia", None))
        self.push_Registro.setText("")
        self.groupBox.setTitle("")
        self.checkBox.setText(QCoreApplication.translate("VentasBD", u"Tarjeta", None))
        self.checkBox_2.setText(QCoreApplication.translate("VentasBD", u"Pago Link", None))
        self.checkBox_3.setText(QCoreApplication.translate("VentasBD", u"Contado Efectivo", None))
        self.checkBox_4.setText(QCoreApplication.translate("VentasBD", u"Efectivo en cuotas", None))
        self.lineEdit_3.setText("")
        self.label_4.setText(QCoreApplication.translate("VentasBD", u"$", None))
        self.label_5.setText(QCoreApplication.translate("VentasBD", u"$", None))
        self.label_6.setText(QCoreApplication.translate("VentasBD", u"$", None))
        self.label_7.setText(QCoreApplication.translate("VentasBD", u"$", None))
        self.label_16.setText(QCoreApplication.translate("VentasBD", u"$", None))
        self.label_3.setText(QCoreApplication.translate("VentasBD", u"Formas de pago", None))
        self.push_Guardar.setText("")
        self.label_29.setText(QCoreApplication.translate("VentasBD", u"TOTAL en PSPV", None))
        self.push_Bcombo.setText(QCoreApplication.translate("VentasBD", u"Buscar Combo", None))
        self.label_10.setText(QCoreApplication.translate("VentasBD", u"DETALLE", None))
        self.lineEdit_7.setText("")
        self.label_26.setText(QCoreApplication.translate("VentasBD", u"Monto en Efectivo", None))
        self.label_8.setText(QCoreApplication.translate("VentasBD", u"Monto a Acreditar ESSEN", None))
        self.lineEdit_8.setText("")
        self.label_13.setText(QCoreApplication.translate("VentasBD", u"PSPV", None))
    # retranslateUi

