# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'VtnaClientes.ui'
##
## Created by: Qt User Interface Compiler version 5.15.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Cliente_BD(object):
    def setupUi(self, Cliente_BD):
        if not Cliente_BD.objectName():
            Cliente_BD.setObjectName(u"Cliente_BD")
        Cliente_BD.resize(1366, 700)
        self.push_Ficha = QPushButton(Cliente_BD)
        self.push_Ficha.setObjectName(u"push_Ficha")
        self.push_Ficha.setGeometry(QRect(1190, 140, 160, 80))
        font = QFont()
        font.setFamily(u"Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.push_Ficha.setFont(font)
        icon = QIcon()
        icon.addFile(u"icon/Ficha.png", QSize(), QIcon.Normal, QIcon.On)
        self.push_Ficha.setIcon(icon)
        self.push_Ficha.setIconSize(QSize(60, 60))
        self.push_Ficha.setAutoDefault(False)
        self.text_Interes = QTextBrowser(Cliente_BD)
        self.text_Interes.setObjectName(u"text_Interes")
        self.text_Interes.setGeometry(QRect(600, 350, 581, 321))
        font1 = QFont()
        font1.setFamily(u"Calibri")
        font1.setBold(False)
        font1.setItalic(False)
        font1.setWeight(50)
        self.text_Interes.setFont(font1)
        self.label_13 = QLabel(Cliente_BD)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 10, 491, 21))
        font2 = QFont()
        font2.setFamily(u"DejaVu Sans")
        font2.setPointSize(18)
        font2.setItalic(True)
        self.label_13.setFont(font2)
        self.label_13.setStyleSheet(u"color: rgb(0, 0, 255);")
        self.label_13.setAlignment(Qt.AlignCenter)
        self.label_8 = QLabel(Cliente_BD)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(500, 10, 671, 21))
        font3 = QFont()
        font3.setFamily(u"Candara")
        font3.setPointSize(18)
        font3.setBold(True)
        font3.setWeight(75)
        self.label_8.setFont(font3)
        self.label_8.setStyleSheet(u"color: rgb(0, 0, 255);")
        self.label_8.setAlignment(Qt.AlignCenter)
        self.push_Nuevo = QPushButton(Cliente_BD)
        self.push_Nuevo.setObjectName(u"push_Nuevo")
        self.push_Nuevo.setGeometry(QRect(1190, 50, 160, 80))
        self.push_Nuevo.setFont(font)
        icon1 = QIcon()
        icon1.addFile(u"icon/agregar persona.png", QSize(), QIcon.Normal, QIcon.On)
        self.push_Nuevo.setIcon(icon1)
        self.push_Nuevo.setIconSize(QSize(60, 60))
        self.push_Nuevo.setAutoDefault(False)
        self.text_Encargado = QTextBrowser(Cliente_BD)
        self.text_Encargado.setObjectName(u"text_Encargado")
        self.text_Encargado.setGeometry(QRect(510, 40, 671, 271))
        self.text_Encargado.setFont(font1)
        self.push_Limpiar = QPushButton(Cliente_BD)
        self.push_Limpiar.setObjectName(u"push_Limpiar")
        self.push_Limpiar.setGeometry(QRect(1190, 280, 160, 80))
        self.push_Limpiar.setFont(font)
        icon2 = QIcon()
        icon2.addFile(u"icon/limpiararchivo2.png", QSize(), QIcon.Normal, QIcon.On)
        self.push_Limpiar.setIcon(icon2)
        self.push_Limpiar.setIconSize(QSize(60, 60))
        self.push_Limpiar.setAutoDefault(False)
        self.label_7 = QLabel(Cliente_BD)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 320, 581, 21))
        self.label_7.setFont(font3)
        self.label_7.setStyleSheet(u"color: rgb(0, 0, 255);")
        self.label_7.setAlignment(Qt.AlignCenter)
        self.text_Comprado = QTextBrowser(Cliente_BD)
        self.text_Comprado.setObjectName(u"text_Comprado")
        self.text_Comprado.setGeometry(QRect(10, 350, 581, 321))
        self.text_Comprado.setFont(font1)
        self.label_9 = QLabel(Cliente_BD)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(600, 320, 571, 21))
        self.label_9.setFont(font3)
        self.label_9.setStyleSheet(u"color: rgb(0, 0, 255);")
        self.label_9.setAlignment(Qt.AlignCenter)
        self.push_Buscar = QPushButton(Cliente_BD)
        self.push_Buscar.setObjectName(u"push_Buscar")
        self.push_Buscar.setGeometry(QRect(1190, 370, 160, 80))
        self.push_Buscar.setFont(font)
        icon3 = QIcon()
        icon3.addFile(u"icon/buscar persona.png", QSize(), QIcon.Normal, QIcon.On)
        self.push_Buscar.setIcon(icon3)
        self.push_Buscar.setIconSize(QSize(60, 60))
        self.push_Buscar.setAutoDefault(False)
        self.groupBox = QGroupBox(Cliente_BD)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 40, 491, 271))
        self.line_Direccion = QLineEdit(self.groupBox)
        self.line_Direccion.setObjectName(u"line_Direccion")
        self.line_Direccion.setGeometry(QRect(180, 180, 291, 31))
        font4 = QFont()
        font4.setFamily(u"Calibri")
        font4.setPointSize(12)
        font4.setBold(False)
        font4.setItalic(False)
        font4.setWeight(50)
        self.line_Direccion.setFont(font4)
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 70, 171, 21))
        font5 = QFont()
        font5.setFamily(u"Javanese Text")
        font5.setPointSize(14)
        font5.setBold(True)
        font5.setWeight(75)
        self.label_3.setFont(font5)
        self.line_Telefono = QLineEdit(self.groupBox)
        self.line_Telefono.setObjectName(u"line_Telefono")
        self.line_Telefono.setGeometry(QRect(180, 140, 291, 31))
        self.line_Telefono.setFont(font4)
        self.Label_2 = QLabel(self.groupBox)
        self.Label_2.setObjectName(u"Label_2")
        self.Label_2.setGeometry(QRect(10, 30, 171, 21))
        self.Label_2.setFont(font5)
        self.line_Dni = QLineEdit(self.groupBox)
        self.line_Dni.setObjectName(u"line_Dni")
        self.line_Dni.setGeometry(QRect(180, 100, 291, 31))
        self.line_Dni.setFont(font4)
        self.line_Apellido = QLineEdit(self.groupBox)
        self.line_Apellido.setObjectName(u"line_Apellido")
        self.line_Apellido.setGeometry(QRect(180, 60, 291, 31))
        self.line_Apellido.setFont(font4)
        self.line_Nombre = QLineEdit(self.groupBox)
        self.line_Nombre.setObjectName(u"line_Nombre")
        self.line_Nombre.setGeometry(QRect(180, 20, 291, 31))
        self.line_Nombre.setFont(font4)
        self.label_11 = QLabel(self.groupBox)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 110, 171, 20))
        self.label_11.setFont(font5)
        self.label_12 = QLabel(self.groupBox)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 150, 171, 21))
        self.label_12.setFont(font5)
        self.label_10 = QLabel(self.groupBox)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 190, 171, 20))
        self.label_10.setFont(font5)
        self.line_Contac1 = QLineEdit(self.groupBox)
        self.line_Contac1.setObjectName(u"line_Contac1")
        self.line_Contac1.setGeometry(QRect(180, 220, 291, 31))
        self.line_Contac1.setFont(font4)
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 230, 171, 21))
        self.label_4.setFont(font5)
        self.push_Registro = QPushButton(Cliente_BD)
        self.push_Registro.setObjectName(u"push_Registro")
        self.push_Registro.setGeometry(QRect(1190, 500, 160, 80))
        self.push_Registro.setFont(font)
        icon4 = QIcon()
        icon4.addFile(u"icon/registros5.png", QSize(), QIcon.Normal, QIcon.On)
        self.push_Registro.setIcon(icon4)
        self.push_Registro.setIconSize(QSize(60, 60))
        self.push_Registro.setAutoDefault(False)
        self.push_Menu = QPushButton(Cliente_BD)
        self.push_Menu.setObjectName(u"push_Menu")
        self.push_Menu.setGeometry(QRect(1190, 590, 160, 80))
        self.push_Menu.setFont(font)
        icon5 = QIcon()
        icon5.addFile(u"icon/home.png", QSize(), QIcon.Normal, QIcon.On)
        self.push_Menu.setIcon(icon5)
        self.push_Menu.setIconSize(QSize(60, 60))
        self.push_Menu.setAutoDefault(False)

        self.retranslateUi(Cliente_BD)

        QMetaObject.connectSlotsByName(Cliente_BD)
    # setupUi

    def retranslateUi(self, Cliente_BD):
        Cliente_BD.setWindowTitle(QCoreApplication.translate("Cliente_BD", u"Dialog", None))
        self.push_Ficha.setText("")
        self.text_Interes.setHtml(QCoreApplication.translate("Cliente_BD", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Calibri'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'MS Shell Dlg 2'; font-size:12pt;\">cacerola cuadrada marsala de 24 - (ANT)</span></p></body></html>", None))
        self.label_13.setText(QCoreApplication.translate("Cliente_BD", u"Datos personales", None))
        self.label_8.setText(QCoreApplication.translate("Cliente_BD", u"EN PROCESO", None))
        self.push_Nuevo.setText("")
        self.text_Encargado.setHtml(QCoreApplication.translate("Cliente_BD", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Calibri'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'MS Shell Dlg 2'; font-size:12pt;\">cacerola cuadrada marsala de 24 - (AL)</span></p></body></html>", None))
        self.push_Limpiar.setText("")
        self.label_7.setText(QCoreApplication.translate("Cliente_BD", u"COMPRADO", None))
        self.text_Comprado.setHtml(QCoreApplication.translate("Cliente_BD", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Calibri'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'MS Shell Dlg 2'; font-size:12pt;\">cacerola cuadrada marsala de 24 - (ANT)</span></p></body></html>", None))
        self.label_9.setText(QCoreApplication.translate("Cliente_BD", u"DESEOS", None))
        self.push_Buscar.setText("")
        self.groupBox.setTitle("")
        self.label_3.setText(QCoreApplication.translate("Cliente_BD", u"TEL\u00c9FONO", None))
        self.Label_2.setText(QCoreApplication.translate("Cliente_BD", u"APE. Y NOMBRE", None))
        self.label_11.setText(QCoreApplication.translate("Cliente_BD", u"FACEBOOK", None))
        self.label_12.setText(QCoreApplication.translate("Cliente_BD", u"INSTAGRAM", None))
        self.label_10.setText(QCoreApplication.translate("Cliente_BD", u"CONTACTO", None))
        self.label_4.setText(QCoreApplication.translate("Cliente_BD", u"CONEXI\u00d3N", None))
        self.push_Registro.setText("")
        self.push_Menu.setText("")
    # retranslateUi

