# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'VtnaBuscar.ui'
##
## Created by: Qt User Interface Compiler version 5.15.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_BuscarProducto(object):
    def setupUi(self, BuscarProducto):
        if not BuscarProducto.objectName():
            BuscarProducto.setObjectName(u"BuscarProducto")
        BuscarProducto.resize(1366, 700)
        self.push_10 = QPushButton(BuscarProducto)
        self.push_10.setObjectName(u"push_10")
        self.push_10.setGeometry(QRect(1050, 170, 191, 131))
        self.push_10.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_10.setAutoDefault(False)
        self.label_2 = QLabel(BuscarProducto)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(480, 130, 191, 20))
        font = QFont()
        font.setFamily(u"Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.push_Bazar = QPushButton(BuscarProducto)
        self.push_Bazar.setObjectName(u"push_Bazar")
        self.push_Bazar.setGeometry(QRect(10, 100, 131, 101))
        font1 = QFont()
        font1.setFamily(u"Arial Black")
        font1.setPointSize(10)
        font1.setBold(True)
        font1.setWeight(75)
        self.push_Bazar.setFont(font1)
        self.push_Bazar.setAutoDefault(False)
        self.push_Aventas = QPushButton(BuscarProducto)
        self.push_Aventas.setObjectName(u"push_Aventas")
        self.push_Aventas.setGeometry(QRect(10, 200, 131, 101))
        self.push_Aventas.setFont(font1)
        self.push_Aventas.setAutoDefault(False)
        self.label_8 = QLabel(BuscarProducto)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(670, 300, 191, 20))
        self.label_8.setFont(font)
        self.label_6 = QLabel(BuscarProducto)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(290, 300, 191, 20))
        self.label_6.setFont(font)
        self.push_Cargar = QPushButton(BuscarProducto)
        self.push_Cargar.setObjectName(u"push_Cargar")
        self.push_Cargar.setGeometry(QRect(10, 600, 131, 101))
        icon = QIcon()
        icon.addFile(u"./icon/cargar.png", QSize(), QIcon.Disabled, QIcon.On)
        self.push_Cargar.setIcon(icon)
        self.push_Cargar.setIconSize(QSize(70, 70))
        self.push_Cargar.setAutoDefault(False)
        self.label_15 = QLabel(BuscarProducto)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(1050, 470, 191, 20))
        self.label_15.setFont(font)
        self.push_2 = QPushButton(BuscarProducto)
        self.push_2.setObjectName(u"push_2")
        self.push_2.setGeometry(QRect(480, 0, 191, 131))
        self.push_2.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_2.setAutoDefault(False)
        self.label_17 = QLabel(BuscarProducto)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(480, 640, 191, 20))
        self.label_17.setFont(font)
        self.push_op1 = QPushButton(BuscarProducto)
        self.push_op1.setObjectName(u"push_op1")
        self.push_op1.setGeometry(QRect(150, 0, 131, 101))
        font2 = QFont()
        font2.setPointSize(12)
        self.push_op1.setFont(font2)
        self.push_op1.setAutoDefault(False)
        self.label_18 = QLabel(BuscarProducto)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(670, 640, 191, 20))
        self.label_18.setFont(font)
        self.push_14 = QPushButton(BuscarProducto)
        self.push_14.setObjectName(u"push_14")
        self.push_14.setGeometry(QRect(860, 340, 191, 131))
        self.push_14.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_14.setAutoDefault(False)
        self.push_20 = QPushButton(BuscarProducto)
        self.push_20.setObjectName(u"push_20")
        self.push_20.setGeometry(QRect(1050, 510, 191, 131))
        self.push_20.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_20.setAutoDefault(False)
        self.push_19 = QPushButton(BuscarProducto)
        self.push_19.setObjectName(u"push_19")
        self.push_19.setGeometry(QRect(860, 510, 191, 131))
        self.push_19.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_19.setAutoDefault(False)
        self.push_8 = QPushButton(BuscarProducto)
        self.push_8.setObjectName(u"push_8")
        self.push_8.setGeometry(QRect(670, 170, 191, 131))
        self.push_8.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_8.setAutoDefault(False)
        self.push_op7 = QPushButton(BuscarProducto)
        self.push_op7.setObjectName(u"push_op7")
        self.push_op7.setGeometry(QRect(150, 600, 131, 101))
        self.push_op7.setFont(font2)
        self.push_op7.setAutoDefault(False)
        self.push_7 = QPushButton(BuscarProducto)
        self.push_7.setObjectName(u"push_7")
        self.push_7.setGeometry(QRect(480, 170, 191, 131))
        self.push_7.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_7.setAutoDefault(False)
        self.push_op3 = QPushButton(BuscarProducto)
        self.push_op3.setObjectName(u"push_op3")
        self.push_op3.setGeometry(QRect(150, 200, 131, 101))
        self.push_op3.setFont(font2)
        self.push_op3.setAutoDefault(False)
        self.push_11 = QPushButton(BuscarProducto)
        self.push_11.setObjectName(u"push_11")
        self.push_11.setGeometry(QRect(290, 340, 191, 131))
        self.push_11.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_11.setAutoDefault(False)
        self.label_14 = QLabel(BuscarProducto)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(860, 470, 191, 20))
        self.label_14.setFont(font)
        self.label_5 = QLabel(BuscarProducto)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(1050, 130, 191, 20))
        self.label_5.setFont(font)
        self.label_7 = QLabel(BuscarProducto)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(480, 300, 191, 20))
        self.label_7.setFont(font)
        self.label_20 = QLabel(BuscarProducto)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(1050, 640, 191, 20))
        self.label_20.setFont(font)
        self.push_Atras = QPushButton(BuscarProducto)
        self.push_Atras.setObjectName(u"push_Atras")
        self.push_Atras.setGeometry(QRect(1250, 40, 111, 311))
        icon1 = QIcon()
        icon1.addFile(u"./icon/anterior.png", QSize(), QIcon.Normal, QIcon.On)
        self.push_Atras.setIcon(icon1)
        self.push_Atras.setIconSize(QSize(60, 60))
        self.push_Atras.setAutoDefault(False)
        self.label_16 = QLabel(BuscarProducto)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(290, 640, 191, 20))
        self.label_16.setFont(font)
        self.push_op5 = QPushButton(BuscarProducto)
        self.push_op5.setObjectName(u"push_op5")
        self.push_op5.setGeometry(QRect(150, 400, 131, 101))
        self.push_op5.setFont(font2)
        self.push_op5.setStyleSheet(u"")
        self.push_op5.setAutoDefault(False)
        self.label_4 = QLabel(BuscarProducto)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(860, 130, 191, 20))
        self.label_4.setFont(font)
        self.label_9 = QLabel(BuscarProducto)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(860, 300, 191, 20))
        self.label_9.setFont(font)
        self.push_op4 = QPushButton(BuscarProducto)
        self.push_op4.setObjectName(u"push_op4")
        self.push_op4.setGeometry(QRect(150, 300, 131, 101))
        self.push_op4.setFont(font2)
        self.push_op4.setAutoDefault(False)
        self.push_17 = QPushButton(BuscarProducto)
        self.push_17.setObjectName(u"push_17")
        self.push_17.setGeometry(QRect(480, 510, 191, 131))
        self.push_17.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_17.setAutoDefault(False)
        self.push_3 = QPushButton(BuscarProducto)
        self.push_3.setObjectName(u"push_3")
        self.push_3.setGeometry(QRect(670, 0, 191, 131))
        self.push_3.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_3.setAutoDefault(False)
        self.push_op2 = QPushButton(BuscarProducto)
        self.push_op2.setObjectName(u"push_op2")
        self.push_op2.setGeometry(QRect(150, 100, 131, 101))
        self.push_op2.setFont(font2)
        self.push_op2.setAutoDefault(False)
        self.push_9 = QPushButton(BuscarProducto)
        self.push_9.setObjectName(u"push_9")
        self.push_9.setGeometry(QRect(860, 170, 191, 131))
        self.push_9.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_9.setAutoDefault(False)
        self.push_12 = QPushButton(BuscarProducto)
        self.push_12.setObjectName(u"push_12")
        self.push_12.setGeometry(QRect(480, 340, 191, 131))
        self.push_12.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_12.setAutoDefault(False)
        self.push_PedidosEsp = QPushButton(BuscarProducto)
        self.push_PedidosEsp.setObjectName(u"push_PedidosEsp")
        self.push_PedidosEsp.setGeometry(QRect(10, 300, 131, 101))
        self.push_PedidosEsp.setFont(font1)
        self.push_PedidosEsp.setAutoDefault(False)
        self.label_3 = QLabel(BuscarProducto)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(670, 130, 191, 20))
        self.label_3.setFont(font)
        self.label_11 = QLabel(BuscarProducto)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(290, 470, 191, 20))
        self.label_11.setFont(font)
        self.label_19 = QLabel(BuscarProducto)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(860, 640, 191, 20))
        self.label_19.setFont(font)
        self.push_18 = QPushButton(BuscarProducto)
        self.push_18.setObjectName(u"push_18")
        self.push_18.setGeometry(QRect(670, 510, 191, 131))
        self.push_18.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_18.setAutoDefault(False)
        self.push_4 = QPushButton(BuscarProducto)
        self.push_4.setObjectName(u"push_4")
        self.push_4.setGeometry(QRect(860, 0, 191, 131))
        self.push_4.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_4.setAutoDefault(False)
        self.push_5 = QPushButton(BuscarProducto)
        self.push_5.setObjectName(u"push_5")
        self.push_5.setGeometry(QRect(1050, 0, 191, 131))
        self.push_5.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_5.setAutoDefault(False)
        self.push_16 = QPushButton(BuscarProducto)
        self.push_16.setObjectName(u"push_16")
        self.push_16.setGeometry(QRect(290, 510, 191, 131))
        self.push_16.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_16.setAutoDefault(False)
        self.push_Adelante = QPushButton(BuscarProducto)
        self.push_Adelante.setObjectName(u"push_Adelante")
        self.push_Adelante.setGeometry(QRect(1250, 340, 111, 311))
        icon2 = QIcon()
        icon2.addFile(u"./icon/siguiente.png", QSize(), QIcon.Normal, QIcon.On)
        self.push_Adelante.setIcon(icon2)
        self.push_Adelante.setIconSize(QSize(60, 60))
        self.push_Adelante.setAutoDefault(False)
        self.push_15 = QPushButton(BuscarProducto)
        self.push_15.setObjectName(u"push_15")
        self.push_15.setGeometry(QRect(1050, 340, 191, 131))
        self.push_15.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_15.setAutoDefault(False)
        self.push_Cancelar = QPushButton(BuscarProducto)
        self.push_Cancelar.setObjectName(u"push_Cancelar")
        self.push_Cancelar.setGeometry(QRect(10, 500, 131, 101))
        icon3 = QIcon()
        icon3.addFile(u"./icon/cancelar2.png", QSize(), QIcon.Disabled, QIcon.On)
        self.push_Cancelar.setIcon(icon3)
        self.push_Cancelar.setIconSize(QSize(70, 70))
        self.push_Cancelar.setAutoDefault(False)
        self.label_10 = QLabel(BuscarProducto)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(1050, 300, 191, 20))
        self.label_10.setFont(font)
        self.push_6 = QPushButton(BuscarProducto)
        self.push_6.setObjectName(u"push_6")
        self.push_6.setGeometry(QRect(290, 170, 191, 131))
        self.push_6.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_6.setAutoDefault(False)
        self.label_12 = QLabel(BuscarProducto)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(480, 470, 191, 20))
        self.label_12.setFont(font)
        self.push_1 = QPushButton(BuscarProducto)
        self.push_1.setObjectName(u"push_1")
        self.push_1.setGeometry(QRect(290, 0, 191, 131))
        self.push_1.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);\n"
"\n"
"\n"
"")
        self.push_1.setAutoDefault(False)
        self.label_1 = QLabel(BuscarProducto)
        self.label_1.setObjectName(u"label_1")
        self.label_1.setGeometry(QRect(290, 130, 191, 20))
        self.label_1.setFont(font)
        self.push_Otros = QPushButton(BuscarProducto)
        self.push_Otros.setObjectName(u"push_Otros")
        self.push_Otros.setGeometry(QRect(10, 400, 131, 101))
        font3 = QFont()
        font3.setFamily(u"Arial Black")
        font3.setPointSize(12)
        font3.setBold(True)
        font3.setWeight(75)
        self.push_Otros.setFont(font3)
        self.push_Otros.setAutoDefault(False)
        self.push_Repuesto = QPushButton(BuscarProducto)
        self.push_Repuesto.setObjectName(u"push_Repuesto")
        self.push_Repuesto.setGeometry(QRect(10, 0, 131, 101))
        self.push_Repuesto.setFont(font3)
        self.push_Repuesto.setAutoDefault(False)
        self.push_op6 = QPushButton(BuscarProducto)
        self.push_op6.setObjectName(u"push_op6")
        self.push_op6.setGeometry(QRect(150, 500, 131, 101))
        self.push_op6.setFont(font2)
        self.push_op6.setAutoDefault(False)
        self.push_13 = QPushButton(BuscarProducto)
        self.push_13.setObjectName(u"push_13")
        self.push_13.setGeometry(QRect(670, 340, 191, 131))
        self.push_13.setStyleSheet(u"\n"
"background-color: rgb(251, 255, 207);\n"
"background-color: rgb(236, 236, 236);")
        self.push_13.setAutoDefault(False)
        self.label_13 = QLabel(BuscarProducto)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(670, 470, 191, 20))
        self.label_13.setFont(font)

        self.retranslateUi(BuscarProducto)

        QMetaObject.connectSlotsByName(BuscarProducto)
    # setupUi

    def retranslateUi(self, BuscarProducto):
        BuscarProducto.setWindowTitle(QCoreApplication.translate("BuscarProducto", u"Dialog", None))
        self.push_10.setText("")
        self.label_2.setText("")
        self.push_Bazar.setText(QCoreApplication.translate("BuscarProducto", u"BAZAR PREMIUM", None))
        self.push_Aventas.setText(QCoreApplication.translate("BuscarProducto", u"AYUDA VNTS", None))
        self.label_8.setText("")
        self.label_6.setText("")
        self.push_Cargar.setText("")
        self.label_15.setText("")
        self.push_2.setText("")
        self.label_17.setText("")
        self.push_op1.setText(QCoreApplication.translate("BuscarProducto", u"-", None))
        self.label_18.setText("")
        self.push_14.setText("")
        self.push_20.setText("")
        self.push_19.setText("")
        self.push_8.setText("")
        self.push_op7.setText(QCoreApplication.translate("BuscarProducto", u"-", None))
        self.push_7.setText("")
        self.push_op3.setText(QCoreApplication.translate("BuscarProducto", u"-", None))
        self.push_11.setText("")
        self.label_14.setText("")
        self.label_5.setText("")
        self.label_7.setText("")
        self.label_20.setText("")
        self.push_Atras.setText("")
        self.label_16.setText("")
        self.push_op5.setText(QCoreApplication.translate("BuscarProducto", u"-", None))
        self.label_4.setText("")
        self.label_9.setText("")
        self.push_op4.setText(QCoreApplication.translate("BuscarProducto", u"-", None))
        self.push_17.setText("")
        self.push_3.setText("")
        self.push_op2.setText(QCoreApplication.translate("BuscarProducto", u"-", None))
        self.push_9.setText("")
        self.push_12.setText("")
        self.push_PedidosEsp.setText(QCoreApplication.translate("BuscarProducto", u"PEDIDOS ESPEC.", None))
        self.label_3.setText("")
        self.label_11.setText("")
        self.label_19.setText("")
        self.push_18.setText("")
        self.push_4.setText("")
        self.push_5.setText("")
        self.push_16.setText("")
        self.push_Adelante.setText("")
        self.push_15.setText("")
        self.push_Cancelar.setText("")
        self.label_10.setText("")
        self.push_6.setText("")
        self.label_12.setText("")
        self.push_1.setText("")
        self.label_1.setText("")
        self.push_Otros.setText(QCoreApplication.translate("BuscarProducto", u"OTROS", None))
        self.push_Repuesto.setText(QCoreApplication.translate("BuscarProducto", u"REPUESTO", None))
        self.push_op6.setText(QCoreApplication.translate("BuscarProducto", u"-", None))
        self.push_13.setText("")
        self.label_13.setText("")
    # retranslateUi

