# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'VtnaProd.ui'
##
## Created by: Qt User Interface Compiler version 5.15.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Productos(object):
    def setupUi(self, Productos):
        if not Productos.objectName():
            Productos.setObjectName(u"Productos")
        Productos.resize(1366, 727)
        self.push_Siguiente = QPushButton(Productos)
        self.push_Siguiente.setObjectName(u"push_Siguiente")
        self.push_Siguiente.setGeometry(QRect(310, 620, 131, 71))
        font = QFont()
        font.setFamily(u"Arial Black")
        font.setPointSize(16)
        font.setItalic(False)
        self.push_Siguiente.setFont(font)
        self.push_Siguiente.setStyleSheet(u"color: rgb(0, 0, 0);")
        icon = QIcon()
        icon.addFile(u"icon/siguiente.png", QSize(), QIcon.Normal, QIcon.On)
        self.push_Siguiente.setIcon(icon)
        self.push_Siguiente.setIconSize(QSize(50, 50))
        self.push_Siguiente.setAutoDefault(False)
        self.groupBox_8 = QGroupBox(Productos)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(590, 570, 321, 111))
        font1 = QFont()
        font1.setFamily(u"DejaVu Sans")
        font1.setPointSize(16)
        font1.setBold(True)
        font1.setItalic(True)
        font1.setWeight(75)
        self.groupBox_8.setFont(font1)
        self.groupBox_8.setStyleSheet(u"color: rgb(0, 0, 255);")
        self.groupBox_8.setAlignment(Qt.AlignCenter)
        self.label_InfoMes = QLabel(self.groupBox_8)
        self.label_InfoMes.setObjectName(u"label_InfoMes")
        self.label_InfoMes.setGeometry(QRect(30, 40, 251, 51))
        font2 = QFont()
        font2.setFamily(u"Javanese Text")
        font2.setPointSize(20)
        font2.setBold(True)
        font2.setItalic(True)
        font2.setWeight(75)
        self.label_InfoMes.setFont(font2)
        self.label_InfoMes.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_InfoMes.setAlignment(Qt.AlignCenter)
        self.push_Guardar = QPushButton(Productos)
        self.push_Guardar.setObjectName(u"push_Guardar")
        self.push_Guardar.setGeometry(QRect(1110, 370, 160, 80))
        font3 = QFont()
        font3.setFamily(u"Arial Black")
        font3.setPointSize(16)
        font3.setBold(True)
        font3.setWeight(75)
        self.push_Guardar.setFont(font3)
        icon1 = QIcon()
        icon1.addFile(u"icon/guardararchivo.png", QSize(), QIcon.Normal, QIcon.On)
        self.push_Guardar.setIcon(icon1)
        self.push_Guardar.setIconSize(QSize(60, 60))
        self.push_Guardar.setAutoDefault(False)
        self.groupBox = QGroupBox(Productos)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 20, 511, 121))
        font4 = QFont()
        font4.setFamily(u"DejaVu Sans")
        font4.setPointSize(18)
        font4.setBold(True)
        font4.setItalic(True)
        font4.setWeight(75)
        self.groupBox.setFont(font4)
        self.groupBox.setStyleSheet(u"color: rgb(0, 0, 255);")
        self.groupBox.setAlignment(Qt.AlignCenter)
        self.label_12 = QLabel(self.groupBox)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(110, 40, 81, 21))
        font5 = QFont()
        font5.setFamily(u"Javanese Text")
        font5.setPointSize(13)
        font5.setBold(True)
        font5.setItalic(True)
        font5.setWeight(75)
        self.label_12.setFont(font5)
        self.label_12.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_12.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(100, 80, 91, 21))
        self.label_2.setFont(font5)
        self.label_2.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.line_Codigo = QLineEdit(self.groupBox)
        self.line_Codigo.setObjectName(u"line_Codigo")
        self.line_Codigo.setGeometry(QRect(200, 70, 141, 31))
        font6 = QFont()
        font6.setFamily(u"Calibri")
        font6.setPointSize(14)
        self.line_Codigo.setFont(font6)
        self.line_Codigo.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.push_Buscar = QPushButton(self.groupBox)
        self.push_Buscar.setObjectName(u"push_Buscar")
        self.push_Buscar.setGeometry(QRect(10, 30, 91, 61))
        self.push_Buscar.setFont(font)
        self.push_Buscar.setStyleSheet(u"color: rgb(0, 0, 0);")
        icon2 = QIcon()
        icon2.addFile(u"icon/buscarlupa.png", QSize(), QIcon.Normal, QIcon.On)
        self.push_Buscar.setIcon(icon2)
        self.push_Buscar.setIconSize(QSize(60, 60))
        self.push_Buscar.setAutoDefault(False)
        self.line_ID = QLineEdit(self.groupBox)
        self.line_ID.setObjectName(u"line_ID")
        self.line_ID.setGeometry(QRect(200, 30, 141, 31))
        self.line_ID.setFont(font6)
        self.line_ID.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.checkBox_Activo = QCheckBox(self.groupBox)
        self.checkBox_Activo.setObjectName(u"checkBox_Activo")
        self.checkBox_Activo.setGeometry(QRect(380, 70, 91, 31))
        font7 = QFont()
        font7.setFamily(u"Arial")
        font7.setPointSize(12)
        font7.setBold(True)
        font7.setItalic(True)
        font7.setWeight(75)
        self.checkBox_Activo.setFont(font7)
        self.checkBox_Activo.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"")
        self.groupBox_5 = QGroupBox(Productos)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(590, 40, 311, 191))
        self.line_PSPV = QLineEdit(self.groupBox_5)
        self.line_PSPV.setObjectName(u"line_PSPV")
        self.line_PSPV.setGeometry(QRect(170, 110, 121, 31))
        self.line_PSPV.setFont(font6)
        self.line_PSPV.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(229, 229, 229);")
        self.line_PSPV.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_9 = QLabel(self.groupBox_5)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(80, 120, 81, 21))
        self.label_9.setFont(font5)
        self.label_9.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_9.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_8 = QLabel(self.groupBox_5)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(-20, 80, 181, 21))
        self.label_8.setFont(font5)
        self.label_8.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_8.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_7 = QLabel(self.groupBox_5)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 40, 141, 21))
        self.label_7.setFont(font5)
        self.label_7.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_7.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.line_Pcio_Lista = QLineEdit(self.groupBox_5)
        self.line_Pcio_Lista.setObjectName(u"line_Pcio_Lista")
        self.line_Pcio_Lista.setGeometry(QRect(170, 150, 121, 31))
        self.line_Pcio_Lista.setFont(font6)
        self.line_Pcio_Lista.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(229, 229, 229);")
        self.line_Pcio_Lista.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.line_Costo10 = QLineEdit(self.groupBox_5)
        self.line_Costo10.setObjectName(u"line_Costo10")
        self.line_Costo10.setGeometry(QRect(170, 70, 121, 31))
        self.line_Costo10.setFont(font6)
        self.line_Costo10.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(229, 229, 229);")
        self.line_Costo10.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_16 = QLabel(self.groupBox_5)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(-20, 160, 181, 21))
        self.label_16.setFont(font5)
        self.label_16.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_16.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.line_Pcio_Costo = QLineEdit(self.groupBox_5)
        self.line_Pcio_Costo.setObjectName(u"line_Pcio_Costo")
        self.line_Pcio_Costo.setGeometry(QRect(170, 30, 121, 31))
        self.line_Pcio_Costo.setFont(font6)
        self.line_Pcio_Costo.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(229, 229, 229);\n"
"")
        self.line_Pcio_Costo.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_17 = QLabel(Productos)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(660, 20, 131, 31))
        self.label_17.setFont(font4)
        self.label_17.setStyleSheet(u"color: rgb(0, 0, 255);")
        self.groupBox_3 = QGroupBox(Productos)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(960, 10, 300, 300))
        font8 = QFont()
        font8.setPointSize(18)
        font8.setItalic(False)
        self.groupBox_3.setFont(font8)
        self.groupBox_3.setAlignment(Qt.AlignCenter)
        self.label_Imagen1 = QLabel(self.groupBox_3)
        self.label_Imagen1.setObjectName(u"label_Imagen1")
        self.label_Imagen1.setGeometry(QRect(0, 0, 300, 300))
        font9 = QFont()
        font9.setFamily(u"Courier")
        font9.setBold(True)
        font9.setWeight(75)
        self.label_Imagen1.setFont(font9)
        self.label_Imagen1.setScaledContents(False)
        self.label_Imagen1.setAlignment(Qt.AlignCenter)
        self.push_Limpiar = QPushButton(Productos)
        self.push_Limpiar.setObjectName(u"push_Limpiar")
        self.push_Limpiar.setGeometry(QRect(1110, 450, 160, 80))
        self.push_Limpiar.setFont(font3)
        icon3 = QIcon()
        icon3.addFile(u"icon/limpiararchivo2.png", QSize(), QIcon.Normal, QIcon.On)
        self.push_Limpiar.setIcon(icon3)
        self.push_Limpiar.setIconSize(QSize(60, 60))
        self.push_Limpiar.setAutoDefault(False)
        self.push_Menu = QPushButton(Productos)
        self.push_Menu.setObjectName(u"push_Menu")
        self.push_Menu.setGeometry(QRect(1110, 610, 160, 80))
        font10 = QFont()
        font10.setFamily(u"Arial Black")
        font10.setPointSize(16)
        font10.setBold(True)
        font10.setItalic(True)
        font10.setWeight(75)
        self.push_Menu.setFont(font10)
        icon4 = QIcon()
        icon4.addFile(u"icon/home.png", QSize(), QIcon.Normal, QIcon.On)
        self.push_Menu.setIcon(icon4)
        self.push_Menu.setIconSize(QSize(60, 60))
        self.push_Menu.setAutoDefault(False)
        self.push_Anterior = QPushButton(Productos)
        self.push_Anterior.setObjectName(u"push_Anterior")
        self.push_Anterior.setGeometry(QRect(170, 620, 131, 71))
        self.push_Anterior.setFont(font)
        self.push_Anterior.setStyleSheet(u"color: rgb(0, 0, 0);")
        icon5 = QIcon()
        icon5.addFile(u"icon/anterior.png", QSize(), QIcon.Normal, QIcon.On)
        self.push_Anterior.setIcon(icon5)
        self.push_Anterior.setIconSize(QSize(50, 50))
        self.push_Anterior.setAutoDefault(False)
        self.groupBox_2 = QGroupBox(Productos)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(60, 140, 461, 361))
        self.groupBox_2.setFont(font4)
        self.groupBox_2.setStyleSheet(u"\n"
"color: rgb(0, 0, 255);")
        self.groupBox_2.setAlignment(Qt.AlignCenter)
        self.comboBox_Linea = QComboBox(self.groupBox_2)
        self.comboBox_Linea.setObjectName(u"comboBox_Linea")
        self.comboBox_Linea.setGeometry(QRect(210, 30, 231, 31))
        self.comboBox_Linea.setFont(font6)
        self.comboBox_Linea.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_4 = QLabel(self.groupBox_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 80, 181, 21))
        self.label_4.setFont(font5)
        self.label_4.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_4.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_14 = QLabel(self.groupBox_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(20, 160, 181, 21))
        self.label_14.setFont(font5)
        self.label_14.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_14.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_13 = QLabel(self.groupBox_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 200, 191, 21))
        self.label_13.setFont(font5)
        self.label_13.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_13.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.line_Repuesto = QLineEdit(self.groupBox_2)
        self.line_Repuesto.setObjectName(u"line_Repuesto")
        self.line_Repuesto.setGeometry(QRect(210, 150, 231, 31))
        self.line_Repuesto.setFont(font6)
        self.line_Repuesto.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_3 = QLabel(self.groupBox_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 40, 181, 21))
        self.label_3.setFont(font5)
        self.label_3.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.line_Bazar = QLineEdit(self.groupBox_2)
        self.line_Bazar.setObjectName(u"line_Bazar")
        self.line_Bazar.setGeometry(QRect(210, 190, 231, 31))
        self.line_Bazar.setFont(font6)
        self.line_Bazar.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.comboBox_Interior = QComboBox(self.groupBox_2)
        self.comboBox_Interior.setObjectName(u"comboBox_Interior")
        self.comboBox_Interior.setGeometry(QRect(210, 110, 231, 31))
        self.comboBox_Interior.setFont(font6)
        self.comboBox_Interior.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_15 = QLabel(self.groupBox_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(20, 120, 181, 21))
        self.label_15.setFont(font5)
        self.label_15.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_15.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.comboBox_Tipo = QComboBox(self.groupBox_2)
        self.comboBox_Tipo.setObjectName(u"comboBox_Tipo")
        self.comboBox_Tipo.setGeometry(QRect(210, 70, 231, 31))
        self.comboBox_Tipo.setFont(font6)
        self.comboBox_Tipo.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.line_Ayudavta = QLineEdit(self.groupBox_2)
        self.line_Ayudavta.setObjectName(u"line_Ayudavta")
        self.line_Ayudavta.setGeometry(QRect(210, 230, 231, 31))
        self.line_Ayudavta.setFont(font6)
        self.line_Ayudavta.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_20 = QLabel(self.groupBox_2)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 240, 191, 21))
        self.label_20.setFont(font5)
        self.label_20.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_20.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.line_Pedido = QLineEdit(self.groupBox_2)
        self.line_Pedido.setObjectName(u"line_Pedido")
        self.line_Pedido.setGeometry(QRect(210, 270, 231, 31))
        self.line_Pedido.setFont(font6)
        self.line_Pedido.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_21 = QLabel(self.groupBox_2)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(10, 280, 191, 21))
        self.label_21.setFont(font5)
        self.label_21.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_21.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.line_Otros = QLineEdit(self.groupBox_2)
        self.line_Otros.setObjectName(u"line_Otros")
        self.line_Otros.setGeometry(QRect(210, 310, 231, 31))
        self.line_Otros.setFont(font6)
        self.line_Otros.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_22 = QLabel(self.groupBox_2)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(10, 320, 191, 21))
        self.label_22.setFont(font5)
        self.label_22.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_22.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_19 = QLabel(Productos)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(640, 250, 111, 31))
        self.label_19.setFont(font4)
        self.label_19.setStyleSheet(u"color: rgb(0, 0, 255);")
        self.push_Excel = QPushButton(Productos)
        self.push_Excel.setObjectName(u"push_Excel")
        self.push_Excel.setGeometry(QRect(1110, 530, 160, 80))
        self.push_Excel.setFont(font3)
        icon6 = QIcon()
        icon6.addFile(u"icon/excel.png", QSize(), QIcon.Normal, QIcon.On)
        self.push_Excel.setIcon(icon6)
        self.push_Excel.setIconSize(QSize(70, 70))
        self.push_Excel.setAutoDefault(False)
        self.groupBox_4 = QGroupBox(Productos)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(60, 500, 461, 111))
        self.groupBox_4.setFont(font4)
        self.groupBox_4.setStyleSheet(u"color: rgb(0, 0, 255);")
        self.groupBox_4.setAlignment(Qt.AlignCenter)
        self.line_Tamanio = QLineEdit(self.groupBox_4)
        self.line_Tamanio.setObjectName(u"line_Tamanio")
        self.line_Tamanio.setGeometry(QRect(200, 30, 111, 31))
        self.line_Tamanio.setFont(font6)
        self.line_Tamanio.setLayoutDirection(Qt.LeftToRight)
        self.line_Tamanio.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.line_Tamanio.setAlignment(Qt.AlignCenter)
        self.label_11 = QLabel(self.groupBox_4)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(320, 40, 31, 21))
        font11 = QFont()
        font11.setFamily(u"Javanese Text")
        font11.setPointSize(14)
        font11.setBold(True)
        font11.setItalic(True)
        font11.setWeight(75)
        self.label_11.setFont(font11)
        self.label_11.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_11.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_10 = QLabel(self.groupBox_4)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(320, 80, 41, 21))
        self.label_10.setFont(font11)
        self.label_10.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_10.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_6 = QLabel(self.groupBox_4)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 80, 181, 21))
        self.label_6.setFont(font5)
        self.label_6.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_6.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.line_Litros = QLineEdit(self.groupBox_4)
        self.line_Litros.setObjectName(u"line_Litros")
        self.line_Litros.setGeometry(QRect(200, 70, 111, 31))
        self.line_Litros.setFont(font6)
        self.line_Litros.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.line_Litros.setAlignment(Qt.AlignCenter)
        self.label_5 = QLabel(self.groupBox_4)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 40, 181, 21))
        self.label_5.setFont(font5)
        self.label_5.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_5.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.groupBox_6 = QGroupBox(Productos)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(590, 270, 311, 111))
        self.line_Puntos_MG = QLineEdit(self.groupBox_6)
        self.line_Puntos_MG.setObjectName(u"line_Puntos_MG")
        self.line_Puntos_MG.setGeometry(QRect(170, 60, 121, 31))
        self.line_Puntos_MG.setFont(font6)
        self.line_Puntos_MG.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.line_Puntos_MG.setAlignment(Qt.AlignCenter)
        self.label_23 = QLabel(self.groupBox_6)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(-20, 30, 181, 31))
        self.label_23.setFont(font5)
        self.label_23.setStyleSheet(u"\n"
"color: rgb(0, 0, 0);")
        self.label_23.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_18 = QLabel(self.groupBox_6)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(-20, 70, 181, 31))
        self.label_18.setFont(font5)
        self.label_18.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_18.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.line_Puntos = QLineEdit(self.groupBox_6)
        self.line_Puntos.setObjectName(u"line_Puntos")
        self.line_Puntos.setGeometry(QRect(170, 20, 121, 31))
        self.line_Puntos.setFont(font6)
        self.line_Puntos.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.line_Puntos.setAlignment(Qt.AlignCenter)
        self.groupBox_7 = QGroupBox(Productos)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(590, 410, 321, 131))
        self.groupBox_7.setFont(font4)
        self.groupBox_7.setStyleSheet(u"color: rgb(0, 0, 255);")
        self.groupBox_7.setAlignment(Qt.AlignCenter)
        self.textEdit_Comentarios = QTextEdit(self.groupBox_7)
        self.textEdit_Comentarios.setObjectName(u"textEdit_Comentarios")
        self.textEdit_Comentarios.setGeometry(QRect(20, 30, 281, 91))
        font12 = QFont()
        font12.setFamily(u"Calibri")
        font12.setPointSize(12)
        self.textEdit_Comentarios.setFont(font12)
        self.textEdit_Comentarios.setStyleSheet(u"color: rgb(0, 0, 0);")

        self.retranslateUi(Productos)

        QMetaObject.connectSlotsByName(Productos)
    # setupUi

    def retranslateUi(self, Productos):
        Productos.setWindowTitle(QCoreApplication.translate("Productos", u"Dialog", None))
        self.push_Siguiente.setText("")
        self.groupBox_8.setTitle(QCoreApplication.translate("Productos", u"Datos de Actualizaci\u00f3n", None))
        self.label_InfoMes.setText(QCoreApplication.translate("Productos", u"-", None))
        self.push_Guardar.setText("")
        self.groupBox.setTitle(QCoreApplication.translate("Productos", u"Identificaci\u00f3n", None))
        self.label_12.setText(QCoreApplication.translate("Productos", u"ID ", None))
        self.label_2.setText(QCoreApplication.translate("Productos", u"CODIGO ", None))
        self.line_Codigo.setText("")
        self.push_Buscar.setText("")
        self.line_ID.setText("")
        self.checkBox_Activo.setText(QCoreApplication.translate("Productos", u"ACTIVO", None))
        self.groupBox_5.setTitle("")
        self.line_PSPV.setText("")
        self.label_9.setText(QCoreApplication.translate("Productos", u"PSPV ", None))
        self.label_8.setText(QCoreApplication.translate("Productos", u"COSTO + 10% ", None))
        self.label_7.setText(QCoreApplication.translate("Productos", u"PCIO. COSTO ", None))
        self.line_Pcio_Lista.setText("")
        self.line_Costo10.setText("")
        self.label_16.setText(QCoreApplication.translate("Productos", u"PCIO. LISTA ", None))
        self.line_Pcio_Costo.setText("")
        self.label_17.setText(QCoreApplication.translate("Productos", u"Costo", None))
        self.groupBox_3.setTitle("")
        self.label_Imagen1.setText(QCoreApplication.translate("Productos", u"SIN IMAGEN", None))
        self.push_Limpiar.setText("")
        self.push_Menu.setText("")
        self.push_Anterior.setText("")
        self.groupBox_2.setTitle(QCoreApplication.translate("Productos", u"Concepto/Tipo", None))
        self.label_4.setText(QCoreApplication.translate("Productos", u"TIPO ", None))
        self.label_14.setText(QCoreApplication.translate("Productos", u"REPUESTOS ", None))
        self.label_13.setText(QCoreApplication.translate("Productos", u"BAZAR PREMIUM ", None))
        self.line_Repuesto.setText("")
        self.label_3.setText(QCoreApplication.translate("Productos", u"L\u00cdNEA ", None))
        self.line_Bazar.setText("")
        self.label_15.setText(QCoreApplication.translate("Productos", u"INTERIOR ", None))
        self.line_Ayudavta.setText("")
        self.label_20.setText(QCoreApplication.translate("Productos", u"AYUDA VTAS ", None))
        self.line_Pedido.setText("")
        self.label_21.setText(QCoreApplication.translate("Productos", u"PED. ESPECIALES ", None))
        self.line_Otros.setText("")
        self.label_22.setText(QCoreApplication.translate("Productos", u"OTROS", None))
        self.label_19.setText(QCoreApplication.translate("Productos", u"Puntos", None))
        self.push_Excel.setText("")
        self.groupBox_4.setTitle(QCoreApplication.translate("Productos", u"Detalles", None))
        self.line_Tamanio.setText("")
        self.label_11.setText(QCoreApplication.translate("Productos", u"Cm", None))
        self.label_10.setText(QCoreApplication.translate("Productos", u"Ltrs", None))
        self.label_6.setText(QCoreApplication.translate("Productos", u"LITROS ", None))
        self.line_Litros.setText("")
        self.label_5.setText(QCoreApplication.translate("Productos", u"TAMA\u00d1O ", None))
        self.groupBox_6.setTitle("")
        self.line_Puntos_MG.setText("")
        self.label_23.setText(QCoreApplication.translate("Productos", u"PUNTOS ", None))
        self.label_18.setText(QCoreApplication.translate("Productos", u"PUNTOS MG ", None))
        self.line_Puntos.setText("")
        self.groupBox_7.setTitle(QCoreApplication.translate("Productos", u"Comentarios", None))
    # retranslateUi

